### ISSUE TITLE
Move metadig-webapp code to metadig-engine repo

### ISSUE THREAD

**Issue by gothub** [NCEAS/mdq-webapp#16]
This repo produces a metadig-webapp war file and a Tomcat based Docker container (metadig-controller) that makes this war available.

This container provides the REST API frontend to metadig-engine. A new version of metadig-webapp and the associated container can be released independently of metadig-engine if the API changes and metadig-engine doesn't.

Are there any other reasons to keep this repo separate from metadig-engine repo?

In the interest of simplifying metadig-engine releases and reducing overhead, I'd like to incorporate the metadig-webapp code into the metadig-engine repo and retire the metadig-webapp repo.

Comments?

**Comment by mbjones** [comment]
In an idealized world, we would use different images for each of the containers, where each image only contained the code needed for that particular container task. Would that be more or less conveniently done in one repo versus multiple. Isn't the evolving best practice is one Dockerfile per repo?

**Comment by gothub** [comment]
Lots of interesting discussion regarding monorepos vs multirepos, if that is what you are referring to:
- https://semaphoreci.com/blog/what-is-monorepo
- https://medium.com/swlh/incremental-docker-builds-for-monolithic-codebases-2dae3ea950e
- https://medium.com/flant-com/monorepo-multirepo-registry-support-in-werf-a73b2a5172d8

I'll close this for now, as the proposed merging of repos doesn't really buy us much at the moment.
